### ISSUE TITLE
Issue With Live Updating

### ISSUE THREAD

**Issue by JelaniThompson** [mattdesl/three-tube-wireframe#1]
Hello there! Really enjoying this package so far and getting some pretty interesting results with my code. I just had a quick question regarding live cycling through the different wireGeometry modes available (quad, triangle, diagonal1, etc.).

Right now in my code, I'm trying to accomplish a functionality that allows me to cycle through all of these by pressing the `u` key. The console is displaying the state as updating, but this isn't reflected in the live view of my geometry unfortunately.

Code: https://gist.github.com/JelaniThompson/fb45f99112f1e745be1b59b5f59af463

I've tried taking a look at the different methods for updating geometries live using this page, but I'm not too sure if I'm applying the examples in the correct way. https://threejs.org/docs/#manual/en/introduction/How-to-update-things

Did you happen to know how I might be able to achieve a functionality like this using three-tube-wireframe specifically? Would really appreciate it!

Thanks,
Jelani

**Comment by mattdesl** [comment]
Hey sorry for the late reply Jelani.

Basically you may need to `dispose()` the old geometry, create a new geometry, and then assign that to your mesh(es).

Hope that helps!
